Version check when packaging.
* Update changelog.json

* Update pack.yml

* Update pack.yml

* Update pack.yml

* Update pack.yml

* Pack v5.10.2

* Delete torntools_5.10.2.zip

* Update changelog.json

* Add check for "v" in entered new version name

Co-authored-by: Sashank999 <Sashank999@users.noreply.github.com>

diff --git a/.github/workflows/pack.yml b/.github/workflows/pack.yml
--- a/.github/workflows/pack.yml
+++ b/.github/workflows/pack.yml
@@ -15,7 +15,18 @@ jobs:
           sudo apt-get install jq
           jqCommand="jq"
           firstEntryLineNo=2
-          firstLineKey="$("${jqCommand}" -j "keys_unsorted[0]" < torntools/changelog.json | tr -d "\"")"
+          allKeys="$("${jqCommand}" -j "keys_unsorted" < torntools/changelog.json)"
+          if grep -q -F "v${{ github.event.inputs.new_version }} - " <<< "$allKeys"
+          then
+              echo "::error file=changelog.json,line=2,col=4::New version entered ${{ github.event.inputs.new_version }} is already present."
+              exit 1
+          fi
+          if grep -q -F "v" <<< "${{ github.event.inputs.new_version }}"
+          then
+              echo "::error file=changelog.json,line=2,col=4::New version entered ${{ github.event.inputs.new_version }} contains \"v\"."
+              exit 1
+          fi
+          firstLineKey="$("${jqCommand}" -j ".[0]" <<< "$allKeys" | tr -d "\"")"
           version="$(echo -n "${firstLineKey}" | cut -d- -f1 | sed 's,^v,,' | tr -d ' ')"
           jqFeatures=".[\"${firstLineKey}\"] | .[\"Features\"]"
           jqFeaturesFull=".[\"${firstLineKey}\"] | .Features | map(sub(\"^\";\"- \";\"m\"))"
